version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: sms_db_mysql
    ports:
      - "3309:3306"
    env_file:
      - .env.local
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:8.0-M02-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env.local
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-backend
    restart: always # on crash restart the container
    env_file:
      - .env.local
    ports:
      - "3001:3001" # as in Dockerfile
    depends_on:
      - db
      - redis

volumes:
  mysql:
  cache:
    driver: local
